version: "3.7"

services:
  app:
    build: ./app
    image: hello-world-flask:v0.1
    ports:
      - target: 80
        published: 8080
        protocol: tcp
    volumes:
      - '.:/app'
    depends_on: 
      - 'redis'
    environment: 
      APP: 'flask'
    env_file:
      - '.env'
      # - '.env.test' # Anything in .env.test file would override the value in .env file
  redis:
    image: redis:3.2-alpine
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    volumes:
      - 'redis:/data'

volumes:
  redis: {}
