version: "3.7"

services:
  sut:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    depends_on :
      - app

  app:
    build: ./app
    image: hello-world-flask:v0.1
    depends_on: 
    - redis

  redis:
    image: redis
