version: "3.7"

services:
  sut:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    depends_on :
      - app
    env_file:
      - '.env'
      - '.env.test' # Anything in .env.test file would override the value in .env file

  app:
    build: ./app
    image: hello-world-flask:v0.1
    depends_on: 
    - redis

  redis:
    image: redis
